version: '3'

services:
  lifestylesante:
    build: 
      context: .
    restart: always
    env_file:
      - .env  # Contient les variables d'environnement pour Django et la base de données
    volumes:
      - static:/app/static
      - medias:/app/medias
    ports:
      - "8000:8000"
    depends_on:
      - db  # Attendre que le service MySQL démarre
    environment:
      - DB_HOST=db  # Adresse du service MySQL
      - DB_PORT=3306  # Port MySQL
      - DB_NAME=${MYSQL_DATABASE}  # Nom de la base de données
      - DB_USER=${MYSQL_USER}  # Utilisateur MySQL
      - DB_PASSWORD=${MYSQL_PASSWORD}  # Mot de passe MySQL
    networks:
      - webnet

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/app/static
      - medias:/app/medias
      - ./certbot/conf:/etc/letsencrypt  # Partage des certificats avec Certbot
      - ./certbot/www:/var/www/certbot   # Dossier pour les challenges Let’s Encrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - lifestylesante
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email support@lifestylesante.org -d lifestylesante.org --agree-tos

    networks:
      - webnet

  db:
    image: mysql:8.0  
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Nom de la base de données
      MYSQL_USER: ${MYSQL_USER}  # Utilisateur MySQL
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Mot de passe MySQL
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Mot de passe root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Stocker les données dans un volume persistant
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db  
    networks:
      - webnet

volumes:
  static:
  medias:
  db_data:

networks:
  webnet:
